// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/elements/badges/pill_with_border_and_dot.vue
<template>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-red-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-yellow-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-green-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-blue-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-indigo-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-purple-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
  <span class="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
    <svg class="size-1.5 fill-pink-400" viewBox="0 0 6 6" aria-hidden="true">
      <circle cx="3" cy="3" r="3" />
    </svg>
    Badge
  </span>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/elements/badges/pill_with_border_and_dot.jsx
export default function ElementsBadgesPillWithBorderAndDot() {
  return (
    <>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-red-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-yellow-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-green-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-blue-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-indigo-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-purple-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
      <span className="inline-flex items-center gap-x-1.5 rounded-full px-2 py-1 text-xs font-medium text-gray-200 inset-ring inset-ring-white/10">
        <svg viewBox="0 0 6 6" aria-hidden="true" className="size-1.5 fill-pink-400">
          <circle r={3} cx={3} cy={3} />
        </svg>
        Badge
      </span>
    </>
  )
}
