// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/forms/input-groups/input_with_gray_background_and_bottom_border.vue
<template>
  <div>
    <label for="name" class="block text-sm/6 font-medium text-white">Name</label>
    <div class="relative mt-2">
      <input type="text" name="name" id="name" class="peer block w-full bg-white/5 px-3 py-1.5 text-white placeholder:text-gray-500 focus:outline-none sm:text-sm/6" placeholder="Jane Smith" />
      <div class="absolute inset-x-0 bottom-0 border-t border-white/20 peer-focus:border-t-2 peer-focus:border-indigo-500" aria-hidden="true" />
    </div>
  </div>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/forms/input-groups/input_with_gray_background_and_bottom_border.jsx
export default function FormsInputGroupsInputWithGrayBackgroundAndBottomBorder() {
  return (
    <div>
      <label htmlFor="name" className="block text-sm/6 font-medium text-white">
        Name
      </label>
      <div className="relative mt-2">
        <input
          id="name"
          name="name"
          type="text"
          placeholder="Jane Smith"
          className="peer block w-full bg-white/5 px-3 py-1.5 text-white placeholder:text-gray-500 focus:outline-none sm:text-sm/6"
        />
        <div
          aria-hidden="true"
          className="absolute inset-x-0 bottom-0 border-t border-white/20 peer-focus:border-t-2 peer-focus:border-indigo-500"
        />
      </div>
    </div>
  )
}
