// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/forms/input-groups/input_with_hidden_label.vue
<template>
  <div>
    <input type="email" name="email" id="email" aria-label="Email" class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6" placeholder="you@example.com" />
  </div>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/forms/input-groups/input_with_hidden_label.jsx
export default function FormsInputGroupsInputWithHiddenLabel() {
  return (
    <div>
      <input
        id="email"
        name="email"
        type="email"
        placeholder="you@example.com"
        aria-label="Email"
        className="block w-full rounded-md bg-white/5 px-3 py-1.5 text-white outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6"
      />
    </div>
  )
}
