// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/elements/badges/small_flat_pill.jsx
export default function ElementsBadgesSmallFlatPill() {
  return (
    <>
      <span className="inline-flex items-center rounded-full bg-gray-800 px-1.5 py-0.5 text-xs font-medium text-gray-300">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-red-400/10 px-1.5 py-0.5 text-xs font-medium text-red-400">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-yellow-400/10 px-1.5 py-0.5 text-xs font-medium text-yellow-300">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-green-400/10 px-1.5 py-0.5 text-xs font-medium text-green-400">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-blue-400/10 px-1.5 py-0.5 text-xs font-medium text-blue-400">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-indigo-400/10 px-1.5 py-0.5 text-xs font-medium text-indigo-400">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-purple-400/10 px-1.5 py-0.5 text-xs font-medium text-purple-400">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-pink-400/10 px-1.5 py-0.5 text-xs font-medium text-pink-400">
        Badge
      </span>
    </>
  )
}

// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/elements/badges/small_flat_pill.vue
<template>
  <span class="inline-flex items-center rounded-full bg-gray-800 px-1.5 py-0.5 text-xs font-medium text-gray-300">Badge</span>
  <span class="inline-flex items-center rounded-full bg-red-400/10 px-1.5 py-0.5 text-xs font-medium text-red-400">Badge</span>
  <span class="inline-flex items-center rounded-full bg-yellow-400/10 px-1.5 py-0.5 text-xs font-medium text-yellow-300">Badge</span>
  <span class="inline-flex items-center rounded-full bg-green-400/10 px-1.5 py-0.5 text-xs font-medium text-green-400">Badge</span>
  <span class="inline-flex items-center rounded-full bg-blue-400/10 px-1.5 py-0.5 text-xs font-medium text-blue-400">Badge</span>
  <span class="inline-flex items-center rounded-full bg-indigo-400/10 px-1.5 py-0.5 text-xs font-medium text-indigo-400">Badge</span>
  <span class="inline-flex items-center rounded-full bg-purple-400/10 px-1.5 py-0.5 text-xs font-medium text-purple-400">Badge</span>
  <span class="inline-flex items-center rounded-full bg-pink-400/10 px-1.5 py-0.5 text-xs font-medium text-pink-400">Badge</span>
</template>
