// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/headings/section-headings/with_description.vue
<template>
  <div class="border-b border-white/10 pb-5">
    <h3 class="text-base font-semibold text-white">Job Postings</h3>
    <p class="mt-2 max-w-4xl text-sm text-gray-400">Workcation is a property rental website. Etiam ullamcorper massa viverra consequat, consectetur id nulla tempus. Fringilla egestas justo massa purus sagittis malesuada.</p>
  </div>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/headings/section-headings/with_description.jsx
export default function HeadingsSectionHeadingsWithDescription() {
  return (
    <div className="border-b border-white/10 pb-5">
      <h3 className="text-base font-semibold text-white">Job Postings</h3>
      <p className="mt-2 max-w-4xl text-sm text-gray-400">
        Workcation is a property rental website. Etiam ullamcorper massa viverra consequat, consectetur id nulla tempus.
        Fringilla egestas justo massa purus sagittis malesuada.
      </p>
    </div>
  )
}
