// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/layout/media-objects/aligned_to_bottom.vue
<template>
  <div class="flex">
    <div class="mr-4 shrink-0 self-end">
      <svg class="size-16 border border-white/15 bg-gray-900 text-white/15" preserveAspectRatio="none" stroke="currentColor" fill="none" viewBox="0 0 200 200" aria-hidden="true">
        <path vector-effect="non-scaling-stroke" stroke-width="1" d="M0 0l200 200M0 200L200 0" />
      </svg>
    </div>
    <div>
      <h4 class="text-lg font-bold text-white">Lorem ipsum</h4>
      <p class="mt-1 text-gray-400">Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus quidem ipsam quia iusto.</p>
    </div>
  </div>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/layout/media-objects/aligned_to_bottom.jsx
export default function LayoutMediaObjectsAlignedToBottom() {
  return (
    <div className="flex">
      <div className="mr-4 shrink-0 self-end">
        <svg
          fill="none"
          stroke="currentColor"
          viewBox="0 0 200 200"
          preserveAspectRatio="none"
          aria-hidden="true"
          className="size-16 border border-white/15 bg-gray-900 text-white/15"
        >
          <path d="M0 0l200 200M0 200L200 0" strokeWidth={1} vectorEffect="non-scaling-stroke" />
        </svg>
      </div>
      <div>
        <h4 className="text-lg font-bold text-white">Lorem ipsum</h4>
        <p className="mt-1 text-gray-400">
          Repudiandae sint consequuntur vel. Amet ut nobis explicabo numquam expedita quia omnis voluptatem. Minus
          quidem ipsam quia iusto.
        </p>
      </div>
    </div>
  )
}
