// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/elements/avatars/with_text.jsx
export default function ElementsAvatarsWithText() {
  return (
    <a href="#" className="group block shrink-0">
      <div className="flex items-center">
        <div>
          <img
            alt=""
            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
            className="inline-block size-9 rounded-full outline -outline-offset-1 outline-white/10"
          />
        </div>
        <div className="ml-3">
          <p className="text-sm font-medium text-gray-300 group-hover:text-white">Tom Cook</p>
          <p className="text-xs font-medium text-gray-400 group-hover:text-gray-300">View profile</p>
        </div>
      </div>
    </a>
  )
}

// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/elements/avatars/with_text.vue
<template>
  <a href="#" class="group block shrink-0">
    <div class="flex items-center">
      <div>
        <img class="inline-block size-9 rounded-full outline -outline-offset-1 outline-white/10" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium text-gray-300 group-hover:text-white">Tom Cook</p>
        <p class="text-xs font-medium text-gray-400 group-hover:text-gray-300">View profile</p>
      </div>
    </div>
  </a>
</template>
