// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/headings/card-headings/with_action.jsx
export default function HeadingsCardHeadingsWithAction() {
  return (
    <div className="border-b border-white/10 px-4 py-5 sm:px-6">
      <div className="-mt-2 -ml-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
        <div className="mt-2 ml-4">
          <h3 className="text-base font-semibold text-white">Job Postings</h3>
        </div>
        <div className="mt-2 ml-4 shrink-0">
          <button
            type="button"
            className="relative inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
          >
            Create new job
          </button>
        </div>
      </div>
    </div>
  )
}

// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/headings/card-headings/with_action.vue
<template>
  <div class="border-b border-white/10 px-4 py-5 sm:px-6">
    <div class="-mt-2 -ml-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="mt-2 ml-4">
        <h3 class="text-base font-semibold text-white">Job Postings</h3>
      </div>
      <div class="mt-2 ml-4 shrink-0">
        <button type="button" class="relative inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Create new job</button>
      </div>
    </div>
  </div>
</template>
