// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/application-ui-tutflix.org/elements/button-groups/basic.jsx
export default function ElementsButtonGroupsBasic() {
  return (
    <span className="isolate inline-flex rounded-md">
      <button
        type="button"
        className="relative inline-flex items-center rounded-l-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10"
      >
        Years
      </button>
      <button
        type="button"
        className="relative -ml-px inline-flex items-center bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10"
      >
        Months
      </button>
      <button
        type="button"
        className="relative -ml-px inline-flex items-center rounded-r-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10"
      >
        Days
      </button>
    </span>
  )
}

// Boilerplate/adamwathanss-tuibeta/v4.1/vue/ui-blocks/application-ui/elements/button-groups/basic.vue
<template>
  <span class="isolate inline-flex rounded-md">
    <button type="button" class="relative inline-flex items-center rounded-l-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10">Years</button>
    <button type="button" class="relative -ml-px inline-flex items-center bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10">Months</button>
    <button type="button" class="relative -ml-px inline-flex items-center rounded-r-md bg-white/10 px-3 py-2 text-sm font-semibold text-white inset-ring-1 inset-ring-gray-700 hover:bg-white/20 focus:z-10">Days</button>
  </span>
</template>
