// Boilerplate/adamwathanss-tuibeta/v3.4/vue/components/marketing/elements/banners/privacy_notice_right_aligned.vue
<template>
  <div class="pointer-events-none fixed inset-x-0 bottom-0 px-6 pb-6">
    <div class="pointer-events-auto ml-auto max-w-xl rounded-xl bg-white p-6 shadow-lg ring-1 ring-gray-900/10">
      <p class="text-sm/6 text-gray-900">This website uses cookies to supplement a balanced diet and provide a much deserved reward to the senses after consuming bland but nutritious meals. Accepting our cookies is optional but recommended, as they are delicious. See our <a href="#" class="font-semibold text-indigo-600">cookie policy</a>.</p>
      <div class="mt-4 flex items-center gap-x-5">
        <button type="button" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-900">Accept all</button>
        <button type="button" class="text-sm/6 font-semibold text-gray-900">Reject all</button>
      </div>
    </div>
  </div>
</template>

// Boilerplate/adamwathanss-tuibeta/v4.1/react/ui-blocks/marketing/elements/banners/privacy_notice_right_aligned.jsx
export default function ElementsBannersPrivacyNoticeRightAligned() {
  return (
    <div className="pointer-events-none fixed inset-x-0 bottom-0 px-6 pb-6">
      <div className="pointer-events-auto ml-auto max-w-xl rounded-xl bg-gray-800 p-6 outline-1 -outline-offset-1 outline-white/10">
        <p className="text-sm/6 text-white">
          This website uses cookies to supplement a balanced diet and provide a much deserved reward to the senses after
          consuming bland but nutritious meals. Accepting our cookies is optional but recommended, as they are
          delicious. See our{' '}
          <a href="#" className="font-semibold text-indigo-400 hover:text-indigo-300">
            cookie policy
          </a>
          .
        </p>
        <div className="mt-4 flex items-center gap-x-5">
          <button
            type="button"
            className="rounded-md bg-gray-700 px-3 py-2 text-sm font-semibold text-white shadow-xs inset-ring inset-ring-white/10 hover:bg-white/15 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
          >
            Accept all
          </button>
          <button type="button" className="text-sm/6 font-semibold text-white hover:text-gray-300">
            Reject all
          </button>
        </div>
      </div>
    </div>
  )
}
